FROM python:3.11

WORKDIR /app

COPY ./requirements.txt /app/

RUN pip install -r /app/requirements.txt

COPY ./DataBases /app/DataBases
COPY ./client.py /app/
COPY ./utils.py /app/

CMD [ "python", "-u", "client.py" ]